import type { WordPair } from "./game.ts";

export const WORD_PAIRS: readonly WordPair[] = [
  { civilian: "牛奶", undercover: "豆浆" },
  { civilian: "手机", undercover: "平板" },
  { civilian: "火锅", undercover: "麻辣烫" },
  { civilian: "饺子", undercover: "馄饨" },
  { civilian: "地铁", undercover: "公交车" },
  { civilian: "电影", undercover: "电视剧" },
  { civilian: "橙子", undercover: "橘子" },
  { civilian: "可乐", undercover: "雪碧" },
  { civilian: "口红", undercover: "唇膏" },
  { civilian: "书店", undercover: "图书馆" },
  { civilian: "雨伞", undercover: "雨衣" },
  { civilian: "医生", undercover: "护士" },
  { civilian: "相机", undercover: "摄像机" },
  { civilian: "电梯", undercover: "扶梯" },
  { civilian: "篮球", undercover: "排球" },
  { civilian: "咖啡", undercover: "奶茶" },
  { civilian: "钱包", undercover: "卡包" },
  { civilian: "耳机", undercover: "音箱" },
  { civilian: "月亮", undercover: "太阳" },
  { civilian: "飞机", undercover: "高铁" },
  { civilian: "牙刷", undercover: "牙膏" },
  { civilian: "西瓜", undercover: "哈密瓜" },
  { civilian: "猫", undercover: "狗" },
  { civilian: "铅笔", undercover: "圆珠笔" },
  { civilian: "枕头", undercover: "抱枕" },
  { civilian: "蛋糕", undercover: "面包" },
  { civilian: "冰箱", undercover: "冰柜" },
  { civilian: "森林", undercover: "草原" },
  { civilian: "啤酒", undercover: "红酒" },
  { civilian: "钥匙", undercover: "门卡" },
] as const;
