import type { WordCategory, WordDifficulty } from "./index.ts";
import type { WordPair } from "./game.ts";

type RawPair = Pick<WordPair, "civilian" | "undercover">;

const BASE_PAIRS: readonly RawPair[] = [
  { civilian: "牛奶", undercover: "豆浆" },
  { civilian: "可乐", undercover: "雪碧" },
  { civilian: "咖啡", undercover: "奶茶" },
  { civilian: "包子", undercover: "馒头" },
  { civilian: "饺子", undercover: "馄饨" },
  { civilian: "火锅", undercover: "麻辣烫" },
  { civilian: "米饭", undercover: "面条" },
  { civilian: "蛋糕", undercover: "面包" },
  { civilian: "西瓜", undercover: "哈密瓜" },
  { civilian: "苹果", undercover: "梨" },
  { civilian: "葡萄", undercover: "提子" },
  { civilian: "草莓", undercover: "樱桃" },
  { civilian: "香蕉", undercover: "芒果" },
  { civilian: "橙子", undercover: "柚子" },
  { civilian: "桃子", undercover: "李子" },
  { civilian: "土豆", undercover: "红薯" },
  { civilian: "黄瓜", undercover: "丝瓜" },
  { civilian: "白菜", undercover: "生菜" },
  { civilian: "芹菜", undercover: "香菜" },
  { civilian: "葱", undercover: "蒜" },
  { civilian: "鸡蛋", undercover: "鸭蛋" },
  { civilian: "鸡肉", undercover: "鸭肉" },
  { civilian: "牛肉", undercover: "羊肉" },
  { civilian: "鱼", undercover: "虾" },
  { civilian: "螃蟹", undercover: "龙虾" },
  { civilian: "盐", undercover: "糖" },
  { civilian: "酱油", undercover: "醋" },
  { civilian: "啤酒", undercover: "白酒" },
  { civilian: "红茶", undercover: "绿茶" },
  { civilian: "冰淇淋", undercover: "雪糕" },
  { civilian: "手机", undercover: "平板" },
  { civilian: "电脑", undercover: "电视" },
  { civilian: "键盘", undercover: "鼠标" },
  { civilian: "耳机", undercover: "音箱" },
  { civilian: "相机", undercover: "摄像机" },
  { civilian: "手表", undercover: "闹钟" },
  { civilian: "电梯", undercover: "楼梯" },
  { civilian: "冰箱", undercover: "空调" },
  { civilian: "洗衣机", undercover: "洗碗机" },
  { civilian: "风扇", undercover: "吹风机" },
  { civilian: "牙刷", undercover: "梳子" },
  { civilian: "毛巾", undercover: "浴巾" },
  { civilian: "牙膏", undercover: "洗面奶" },
  { civilian: "洗发水", undercover: "沐浴露" },
  { civilian: "雨伞", undercover: "雨衣" },
  { civilian: "鞋子", undercover: "袜子" },
  { civilian: "帽子", undercover: "围巾" },
  { civilian: "手套", undercover: "口罩" },
  { civilian: "背包", undercover: "手提包" },
  { civilian: "钥匙", undercover: "门卡" },
  { civilian: "铅笔", undercover: "圆珠笔" },
  { civilian: "橡皮", undercover: "尺子" },
  { civilian: "书包", undercover: "文具盒" },
  { civilian: "课本", undercover: "作业本" },
  { civilian: "黑板", undercover: "白板" },
  { civilian: "教室", undercover: "图书馆" },
  { civilian: "老师", undercover: "校长" },
  { civilian: "学生", undercover: "班长" },
  { civilian: "考试", undercover: "作业" },
  { civilian: "语文", undercover: "数学" },
  { civilian: "篮球", undercover: "足球" },
  { civilian: "羽毛球", undercover: "乒乓球" },
  { civilian: "游泳", undercover: "跑步" },
  { civilian: "跳绳", undercover: "踢毽子" },
  { civilian: "公园", undercover: "广场" },
  { civilian: "超市", undercover: "菜市场" },
  { civilian: "医院", undercover: "药店" },
  { civilian: "银行", undercover: "邮局" },
  { civilian: "酒店", undercover: "民宿" },
  { civilian: "地铁", undercover: "公交车" },
  { civilian: "出租车", undercover: "网约车" },
  { civilian: "高铁", undercover: "火车" },
  { civilian: "飞机", undercover: "轮船" },
  { civilian: "自行车", undercover: "电动车" },
  { civilian: "红绿灯", undercover: "路灯" },
  { civilian: "公路", undercover: "铁路" },
  { civilian: "猫", undercover: "狗" },
  { civilian: "老虎", undercover: "狮子" },
  { civilian: "大象", undercover: "长颈鹿" },
  { civilian: "熊猫", undercover: "北极熊" },
  { civilian: "猴子", undercover: "猩猩" },
  { civilian: "兔子", undercover: "松鼠" },
  { civilian: "鸭子", undercover: "鹅" },
  { civilian: "鸡", undercover: "鹌鹑" },
  { civilian: "蝴蝶", undercover: "蜜蜂" },
  { civilian: "蚂蚁", undercover: "蜘蛛" },
  { civilian: "鲨鱼", undercover: "鲸鱼" },
  { civilian: "海豚", undercover: "海豹" },
  { civilian: "企鹅", undercover: "鸵鸟" },
  { civilian: "青蛙", undercover: "蟾蜍" },
  { civilian: "春天", undercover: "秋天" },
  { civilian: "夏天", undercover: "冬天" },
  { civilian: "白天", undercover: "夜晚" },
  { civilian: "晴天", undercover: "阴天" },
  { civilian: "下雨", undercover: "下雪" },
  { civilian: "太阳", undercover: "月亮" },
  { civilian: "星星", undercover: "云朵" },
  { civilian: "高山", undercover: "丘陵" },
  { civilian: "大海", undercover: "湖泊" },
  { civilian: "河流", undercover: "小溪" },
  { civilian: "电影", undercover: "电视剧" },
  { civilian: "动画片", undercover: "漫画" },
  { civilian: "小说", undercover: "散文" },
  { civilian: "诗歌", undercover: "歌词" },
  { civilian: "相声", undercover: "小品" },
  { civilian: "话剧", undercover: "歌剧" },
  { civilian: "演员", undercover: "歌手" },
  { civilian: "导演", undercover: "编剧" },
  { civilian: "主持人", undercover: "记者" },
  { civilian: "观众", undercover: "听众" },
  { civilian: "电影院", undercover: "剧院" },
  { civilian: "舞台", undercover: "片场" },
  { civilian: "海报", undercover: "门票" },
  { civilian: "直播", undercover: "录播" },
  { civilian: "综艺", undercover: "纪录片" },
  { civilian: "喜剧", undercover: "悲剧" },
  { civilian: "悬疑", undercover: "推理" },
  { civilian: "科幻", undercover: "奇幻" },
  { civilian: "古装", undercover: "现代剧" },
  { civilian: "配音", undercover: "旁白" },
  { civilian: "短信", undercover: "电话" },
  { civilian: "视频通话", undercover: "语音通话" },
  { civilian: "群聊", undercover: "私聊" },
  { civilian: "朋友圈", undercover: "动态" },
  { civilian: "点赞", undercover: "收藏" },
  { civilian: "评论", undercover: "转发" },
  { civilian: "搜索", undercover: "浏览" },
  { civilian: "下载", undercover: "上传" },
  { civilian: "登录", undercover: "注册" },
  { civilian: "密码", undercover: "验证码" },
  { civilian: "浏览器", undercover: "搜索引擎" },
  { civilian: "网页", undercover: "网站" },
  { civilian: "文件", undercover: "文件夹" },
  { civilian: "复制", undercover: "粘贴" },
  { civilian: "删除", undercover: "撤销" },
  { civilian: "截图", undercover: "录屏" },
  { civilian: "扫码", undercover: "刷脸" },
  { civilian: "充电", undercover: "省电" },
  { civilian: "信号", undercover: "网络" },
  { civilian: "蓝牙", undercover: "WiFi" },
  { civilian: "上班", undercover: "上学" },
  { civilian: "加班", undercover: "值班" },
  { civilian: "请假", undercover: "调休" },
  { civilian: "工资", undercover: "奖金" },
  { civilian: "简历", undercover: "合同" },
  { civilian: "面试", undercover: "试用" },
  { civilian: "同事", undercover: "同学" },
  { civilian: "老板", undercover: "经理" },
  { civilian: "客户", undercover: "顾客" },
  { civilian: "会议", undercover: "培训" },
  { civilian: "前台", undercover: "收银台" },
  { civilian: "办公室", undercover: "会议室" },
  { civilian: "打卡", undercover: "签到" },
  { civilian: "出差", undercover: "旅行" },
  { civilian: "出租", undercover: "租借" },
  { civilian: "快递", undercover: "外卖" },
  { civilian: "快递员", undercover: "外卖员" },
  { civilian: "商场", undercover: "商店" },
  { civilian: "餐厅", undercover: "食堂" },
  { civilian: "咖啡馆", undercover: "茶馆" },
  { civilian: "理发店", undercover: "美容院" },
  { civilian: "健身房", undercover: "体育馆" },
  { civilian: "博物馆", undercover: "美术馆" },
  { civilian: "动物园", undercover: "植物园" },
  { civilian: "游乐园", undercover: "水上乐园" },
  { civilian: "景区", undercover: "度假村" },
  { civilian: "机场", undercover: "车站" },
  { civilian: "站台", undercover: "候机厅" },
  { civilian: "车票", undercover: "机票" },
  { civilian: "行李", undercover: "箱包" },
  { civilian: "护照", undercover: "身份证" },
  { civilian: "地图", undercover: "导航" },
  { civilian: "红包", undercover: "礼物" },
  { civilian: "生日", undercover: "纪念日" },
  { civilian: "婚礼", undercover: "宴会" },
  { civilian: "聚会", undercover: "团建" },
  { civilian: "春节", undercover: "元宵节" },
  { civilian: "端午节", undercover: "中秋节" },
  { civilian: "七夕", undercover: "情人节" },
  { civilian: "圣诞节", undercover: "元旦" },
  { civilian: "鲜花", undercover: "绿植" },
  { civilian: "玫瑰", undercover: "百合" },
  { civilian: "竹子", undercover: "柳树" },
  { civilian: "松树", undercover: "柏树" },
  { civilian: "荷花", undercover: "睡莲" },
  { civilian: "仙人掌", undercover: "多肉" },
  { civilian: "草坪", undercover: "操场" },
  { civilian: "森林", undercover: "草原" },
  { civilian: "沙漠", undercover: "戈壁" },
  { civilian: "瀑布", undercover: "喷泉" },
  { civilian: "洞穴", undercover: "隧道" },
  { civilian: "岛屿", undercover: "半岛" },
  { civilian: "沙滩", undercover: "海岸" },
  { civilian: "日出", undercover: "日落" },
  { civilian: "彩虹", undercover: "极光" },
  { civilian: "雾", undercover: "霜" },
  { civilian: "台风", undercover: "龙卷风" },
  { civilian: "闪电", undercover: "雷声" },
  { civilian: "微风", undercover: "大风" },
  { civilian: "温度", undercover: "湿度" },
  { civilian: "医生", undercover: "护士" },
  { civilian: "牙医", undercover: "兽医" },
  { civilian: "警察", undercover: "保安" },
  { civilian: "消防员", undercover: "救生员" },
  { civilian: "律师", undercover: "法官" },
  { civilian: "会计", undercover: "出纳" },
  { civilian: "设计师", undercover: "工程师" },
  { civilian: "程序员", undercover: "测试员" },
  { civilian: "厨师", undercover: "烘焙师" },
  { civilian: "导游", undercover: "领队" },
  { civilian: "飞行员", undercover: "空乘" },
  { civilian: "司机", undercover: "骑手" },
  { civilian: "摄影师", undercover: "化妆师" },
  { civilian: "裁缝", undercover: "理发师" },
  { civilian: "木匠", undercover: "电工" },
  { civilian: "画家", undercover: "书法家" },
  { civilian: "作家", undercover: "编辑" },
  { civilian: "翻译", undercover: "配音员" },
  { civilian: "教练", undercover: "裁判" },
  { civilian: "运动员", undercover: "模特" },
  { civilian: "口红", undercover: "唇膏" },
  { civilian: "粉底", undercover: "遮瑕" },
  { civilian: "眼影", undercover: "腮红" },
  { civilian: "香水", undercover: "护肤品" },
  { civilian: "项链", undercover: "手链" },
  { civilian: "戒指", undercover: "耳环" },
  { civilian: "西装", undercover: "礼服" },
  { civilian: "衬衫", undercover: "T恤" },
  { civilian: "牛仔裤", undercover: "休闲裤" },
  { civilian: "皮鞋", undercover: "运动鞋" },
  { civilian: "高跟鞋", undercover: "凉鞋" },
  { civilian: "拖鞋", undercover: "雨靴" },
  { civilian: "羽绒服", undercover: "风衣" },
  { civilian: "毛衣", undercover: "卫衣" },
  { civilian: "睡衣", undercover: "浴袍" },
  { civilian: "领带", undercover: "领结" },
  { civilian: "墨镜", undercover: "眼镜" },
  { civilian: "发卡", undercover: "发箍" },
  { civilian: "钱包", undercover: "卡包" },
  { civilian: "行李箱", undercover: "收纳箱" },
  { civilian: "菜刀", undercover: "剪刀" },
  { civilian: "锅", undercover: "铲" },
  { civilian: "筷子", undercover: "勺子" },
  { civilian: "碗", undercover: "盘子" },
  { civilian: "水杯", undercover: "保温杯" },
  { civilian: "茶壶", undercover: "水壶" },
  { civilian: "微波炉", undercover: "烤箱" },
  { civilian: "电饭煲", undercover: "电压力锅" },
  { civilian: "榨汁机", undercover: "豆浆机" },
  { civilian: "吸尘器", undercover: "扫地机器人" },
  { civilian: "沙发", undercover: "躺椅" },
  { civilian: "床", undercover: "榻榻米" },
  { civilian: "衣柜", undercover: "鞋柜" },
  { civilian: "书桌", undercover: "餐桌" },
  { civilian: "台灯", undercover: "吊灯" },
  { civilian: "窗帘", undercover: "百叶窗" },
  { civilian: "地毯", undercover: "地垫" },
  { civilian: "枕头", undercover: "抱枕" },
  { civilian: "被子", undercover: "毛毯" },
  { civilian: "阳台", undercover: "露台" },
  { civilian: "客厅", undercover: "卧室" },
  { civilian: "厨房", undercover: "卫生间" },
  { civilian: "门把手", undercover: "门铃" },
  { civilian: "插座", undercover: "开关" },
  { civilian: "水龙头", undercover: "花洒" },
  { civilian: "马桶", undercover: "洗手盆" },
  { civilian: "镜子", undercover: "相框" },
  { civilian: "挂钟", undercover: "台历" },
  { civilian: "垃圾桶", undercover: "收纳筐" },
  { civilian: "晾衣架", undercover: "衣帽架" },
  { civilian: "豆腐", undercover: "豆皮" },
  { civilian: "粉条", undercover: "粉皮" },
  { civilian: "年糕", undercover: "糍粑" },
  { civilian: "汤圆", undercover: "元宵" },
  { civilian: "油条", undercover: "麻花" },
  { civilian: "烧饼", undercover: "锅盔" },
  { civilian: "粽子", undercover: "饭团" },
  { civilian: "寿司", undercover: "紫菜包饭" },
  { civilian: "汉堡", undercover: "三明治" },
  { civilian: "披萨", undercover: "馅饼" },
  { civilian: "炒饭", undercover: "盖饭" },
  { civilian: "拉面", undercover: "米线" },
  { civilian: "螺蛳粉", undercover: "酸辣粉" },
  { civilian: "烤鸭", undercover: "烧鹅" },
  { civilian: "烤肉", undercover: "烧烤" },
  { civilian: "红烧肉", undercover: "回锅肉" },
  { civilian: "宫保鸡丁", undercover: "辣子鸡" },
  { civilian: "鱼香肉丝", undercover: "京酱肉丝" },
  { civilian: "酸菜鱼", undercover: "水煮鱼" },
  { civilian: "蒸饺", undercover: "锅贴" },
  { civilian: "蛋挞", undercover: "泡芙" },
  { civilian: "曲奇", undercover: "饼干" },
  { civilian: "巧克力", undercover: "糖果" },
  { civilian: "果冻", undercover: "布丁" },
  { civilian: "蜂蜜", undercover: "果酱" },
  { civilian: "酸奶", undercover: "奶酪" },
  { civilian: "橙汁", undercover: "苹果汁" },
  { civilian: "柠檬水", undercover: "苏打水" },
  { civilian: "冰沙", undercover: "奶昔" },
  { civilian: "豆花", undercover: "双皮奶" },
  { civilian: "存款", undercover: "理财" },
  { civilian: "股票", undercover: "基金" },
  { civilian: "现金", undercover: "银行卡" },
  { civilian: "信用卡", undercover: "借记卡" },
  { civilian: "转账", undercover: "汇款" },
  { civilian: "付款", undercover: "收款" },
  { civilian: "退款", undercover: "退货" },
  { civilian: "发票", undercover: "收据" },
  { civilian: "订单", undercover: "账单" },
  { civilian: "折扣", undercover: "优惠券" },
  { civilian: "定金", undercover: "押金" },
  { civilian: "房租", undercover: "房贷" },
  { civilian: "工资条", undercover: "银行流水" },
  { civilian: "预算", undercover: "决算" },
  { civilian: "收入", undercover: "支出" },
  { civilian: "成本", undercover: "利润" },
  { civilian: "资产", undercover: "负债" },
  { civilian: "股东", undercover: "合伙人" },
  { civilian: "创业", undercover: "投资" },
  { civilian: "商标", undercover: "专利" },
  { civilian: "申请", undercover: "审批" },
  { civilian: "预约", undercover: "排队" },
  { civilian: "挂号", undercover: "取号" },
  { civilian: "报名", undercover: "报到" },
  { civilian: "登机", undercover: "值机" },
  { civilian: "入住", undercover: "退房" },
  { civilian: "借书", undercover: "还书" },
  { civilian: "签收", undercover: "拒收" },
  { civilian: "缴费", undercover: "充值" },
  { civilian: "报修", undercover: "维修" },
  { civilian: "备份", undercover: "恢复" },
  { civilian: "安装", undercover: "卸载" },
  { civilian: "更新", undercover: "升级" },
  { civilian: "开机", undercover: "重启" },
  { civilian: "静音", undercover: "免打扰" },
  { civilian: "公开", undercover: "私密" },
  { civilian: "在线", undercover: "离线" },
  { civilian: "原图", undercover: "滤镜" },
  { civilian: "草稿", undercover: "正文" },
  { civilian: "标题", undercover: "摘要" },
  { civilian: "目录", undercover: "索引" },
  { civilian: "附件", undercover: "链接" },
  { civilian: "通知", undercover: "公告" },
  { civilian: "提醒音", undercover: "闹铃" },
  { civilian: "收藏夹", undercover: "回收站" },
  { civilian: "账号", undercover: "昵称" },
  { civilian: "头像", undercover: "封面" },
  { civilian: "关注", undercover: "订阅" },
  { civilian: "粉丝", undercover: "好友" },
  { civilian: "热搜", undercover: "榜单" },
  { civilian: "片头", undercover: "片尾" },
  { civilian: "预告", undercover: "花絮" },
  { civilian: "主角", undercover: "配角" },
  { civilian: "台词", undercover: "剧本" },
  { civilian: "镜头", undercover: "画面" },
  { civilian: "特写", undercover: "全景" },
  { civilian: "字幕", undercover: "弹幕" },
  { civilian: "原声", undercover: "配乐" },
  { civilian: "首映", undercover: "重映" },
  { civilian: "连载", undercover: "完结" },
  { civilian: "章节", undercover: "段落" },
  { civilian: "序言", undercover: "后记" },
  { civilian: "作者", undercover: "读者" },
  { civilian: "出版", undercover: "印刷" },
  { civilian: "纸质书", undercover: "电子书" },
  { civilian: "字典", undercover: "词典" },
  { civilian: "成语", undercover: "谚语" },
  { civilian: "近义词", undercover: "反义词" },
  { civilian: "主语", undercover: "谓语" },
  { civilian: "单数", undercover: "复数" },
  { civilian: "加法", undercover: "乘法" },
  { civilian: "分数", undercover: "小数" },
  { civilian: "方程", undercover: "函数" },
  { civilian: "直线", undercover: "曲线" },
  { civilian: "圆形", undercover: "椭圆" },
  { civilian: "正方形", undercover: "长方形" },
  { civilian: "面积", undercover: "体积" },
  { civilian: "长度", undercover: "高度" },
  { civilian: "速度", undercover: "加速度" },
  { civilian: "重力", undercover: "浮力" },
  { civilian: "固体", undercover: "液体" },
  { civilian: "蒸发", undercover: "沸腾" },
  { civilian: "融化", undercover: "凝固" },
  { civilian: "酸性", undercover: "碱性" },
  { civilian: "氧气", undercover: "二氧化碳" },
  { civilian: "细胞", undercover: "细菌" },
  { civilian: "病毒", undercover: "真菌" },
  { civilian: "骨骼", undercover: "肌肉" },
  { civilian: "心脏", undercover: "肺" },
  { civilian: "胃", undercover: "肠" },
  { civilian: "大脑", undercover: "小脑" },
  { civilian: "血管", undercover: "神经" },
  { civilian: "温度计", undercover: "体温计" },
  { civilian: "显微镜", undercover: "望远镜" },
  { civilian: "磁铁", undercover: "指南针" },
  { civilian: "电池", undercover: "电源" },
  { civilian: "电压", undercover: "电流" },
  { civilian: "芯片", undercover: "电路板" },
  { civilian: "内存", undercover: "硬盘" },
  { civilian: "像素", undercover: "分辨率" },
] as const;

const CURATED_PAIRS: readonly WordPair[] = [
  // 欢乐搞笑：高共鸣、低门槛，重点是描述空间而非网络黑话。
  { civilian: "社恐", undercover: "社牛", category: "FUNNY", difficulty: "EASY", audience: "GENERAL" },
  { civilian: "摸鱼", undercover: "赶进度", category: "FUNNY", difficulty: "EASY", audience: "GENERAL" },
  { civilian: "早八", undercover: "熬夜", category: "FUNNY", difficulty: "EASY", audience: "GENERAL" },
  { civilian: "自拍", undercover: "他拍", category: "FUNNY", difficulty: "EASY", audience: "GENERAL" },
  { civilian: "表情包", undercover: "斗图", category: "FUNNY", difficulty: "EASY", audience: "GENERAL" },
  { civilian: "夹娃娃", undercover: "抽盲盒", category: "FUNNY", difficulty: "STANDARD", audience: "GENERAL" },
  { civilian: "赖床", undercover: "回笼觉", category: "FUNNY", difficulty: "STANDARD", audience: "GENERAL" },
  { civilian: "忘带钥匙", undercover: "忘带手机", category: "FUNNY", difficulty: "STANDARD", audience: "GENERAL" },
  { civilian: "抢红包", undercover: "拼手速", category: "FUNNY", difficulty: "STANDARD", audience: "GENERAL" },
  { civilian: "放鸽子", undercover: "迟到", category: "FUNNY", difficulty: "EASY", audience: "GENERAL" },
  { civilian: "拍马屁", undercover: "彩虹屁", category: "FUNNY", difficulty: "STANDARD", audience: "GENERAL" },
  { civilian: "吃瓜群众", undercover: "围观群众", category: "FUNNY", difficulty: "STANDARD", audience: "GENERAL" },
  { civilian: "显眼包", undercover: "气氛组", category: "FUNNY", difficulty: "STANDARD", audience: "GENERAL" },
  { civilian: "碎碎念", undercover: "自言自语", category: "FUNNY", difficulty: "STANDARD", audience: "GENERAL" },
  { civilian: "路痴", undercover: "脸盲", category: "FUNNY", difficulty: "EASY", audience: "GENERAL" },
  { civilian: "选择困难", undercover: "拖延症", category: "FUNNY", difficulty: "STANDARD", audience: "GENERAL" },
  { civilian: "冷笑话", undercover: "谐音梗", category: "FUNNY", difficulty: "STANDARD", audience: "GENERAL" },
  { civilian: "蹭饭", undercover: "打包", category: "FUNNY", difficulty: "EASY", audience: "GENERAL" },
  { civilian: "甩锅", undercover: "背锅", category: "FUNNY", difficulty: "STANDARD", audience: "GENERAL" },
  { civilian: "画大饼", undercover: "灌鸡汤", category: "FUNNY", difficulty: "HARD", audience: "GENERAL" },
  { civilian: "空耳", undercover: "听岔", category: "FUNNY", difficulty: "STANDARD", audience: "GENERAL" },
  { civilian: "蹭网", undercover: "借充电宝", category: "FUNNY", difficulty: "STANDARD", audience: "GENERAL" },
  { civilian: "已读不回", undercover: "正在输入", category: "FUNNY", difficulty: "STANDARD", audience: "GENERAL" },
  { civilian: "网抑云", undercover: "深夜emo", category: "FUNNY", difficulty: "HARD", audience: "GENERAL" },
  { civilian: "假装听懂", undercover: "不懂装懂", category: "FUNNY", difficulty: "STANDARD", audience: "GENERAL" },
  { civilian: "临时抱佛脚", undercover: "考前突击", category: "FUNNY", difficulty: "STANDARD", audience: "GENERAL" },
  { civilian: "手滑点赞", undercover: "误发消息", category: "FUNNY", difficulty: "STANDARD", audience: "GENERAL" },
  { civilian: "人菜瘾大", undercover: "又菜又爱玩", category: "FUNNY", difficulty: "HARD", audience: "GENERAL" },
  { civilian: "嘴硬", undercover: "心虚", category: "FUNNY", difficulty: "EASY", audience: "GENERAL" },
  { civilian: "凑热闹", undercover: "赶时髦", category: "FUNNY", difficulty: "STANDARD", audience: "GENERAL" },

  // 成语文化。
  { civilian: "画蛇添足", undercover: "多此一举", category: "IDIOM", difficulty: "EASY", audience: "GENERAL" },
  { civilian: "守株待兔", undercover: "刻舟求剑", category: "IDIOM", difficulty: "STANDARD", audience: "GENERAL" },
  { civilian: "掩耳盗铃", undercover: "自欺欺人", category: "IDIOM", difficulty: "STANDARD", audience: "GENERAL" },
  { civilian: "亡羊补牢", undercover: "未雨绸缪", category: "IDIOM", difficulty: "STANDARD", audience: "GENERAL" },
  { civilian: "雪中送炭", undercover: "锦上添花", category: "IDIOM", difficulty: "EASY", audience: "GENERAL" },
  { civilian: "狐假虎威", undercover: "仗势欺人", category: "IDIOM", difficulty: "STANDARD", audience: "GENERAL" },
  { civilian: "井底之蛙", undercover: "坐井观天", category: "IDIOM", difficulty: "EASY", audience: "GENERAL" },
  { civilian: "杯弓蛇影", undercover: "草木皆兵", category: "IDIOM", difficulty: "HARD", audience: "GENERAL" },
  { civilian: "闻鸡起舞", undercover: "悬梁刺股", category: "IDIOM", difficulty: "HARD", audience: "GENERAL" },
  { civilian: "滥竽充数", undercover: "鱼目混珠", category: "IDIOM", difficulty: "STANDARD", audience: "GENERAL" },
  { civilian: "对牛弹琴", undercover: "鸡同鸭讲", category: "IDIOM", difficulty: "EASY", audience: "GENERAL" },
  { civilian: "叶公好龙", undercover: "口是心非", category: "IDIOM", difficulty: "HARD", audience: "GENERAL" },
  { civilian: "盲人摸象", undercover: "管中窥豹", category: "IDIOM", difficulty: "HARD", audience: "GENERAL" },
  { civilian: "鹤立鸡群", undercover: "脱颖而出", category: "IDIOM", difficulty: "STANDARD", audience: "GENERAL" },
  { civilian: "虎头蛇尾", undercover: "有始无终", category: "IDIOM", difficulty: "STANDARD", audience: "GENERAL" },
  { civilian: "一箭双雕", undercover: "一举两得", category: "IDIOM", difficulty: "EASY", audience: "GENERAL" },
  { civilian: "破釜沉舟", undercover: "背水一战", category: "IDIOM", difficulty: "STANDARD", audience: "GENERAL" },
  { civilian: "纸上谈兵", undercover: "夸夸其谈", category: "IDIOM", difficulty: "HARD", audience: "GENERAL" },
  { civilian: "东山再起", undercover: "卷土重来", category: "IDIOM", difficulty: "STANDARD", audience: "GENERAL" },
  { civilian: "四面楚歌", undercover: "腹背受敌", category: "IDIOM", difficulty: "HARD", audience: "GENERAL" },
  { civilian: "指鹿为马", undercover: "颠倒黑白", category: "IDIOM", difficulty: "STANDARD", audience: "GENERAL" },
  { civilian: "三顾茅庐", undercover: "礼贤下士", category: "IDIOM", difficulty: "HARD", audience: "GENERAL" },
  { civilian: "望梅止渴", undercover: "画饼充饥", category: "IDIOM", difficulty: "STANDARD", audience: "GENERAL" },
  { civilian: "水滴石穿", undercover: "铁杵成针", category: "IDIOM", difficulty: "STANDARD", audience: "GENERAL" },
  { civilian: "胸有成竹", undercover: "成竹在胸", category: "IDIOM", difficulty: "EASY", audience: "GENERAL" },
  { civilian: "惊弓之鸟", undercover: "漏网之鱼", category: "IDIOM", difficulty: "HARD", audience: "GENERAL" },
  { civilian: "风吹草动", undercover: "蛛丝马迹", category: "IDIOM", difficulty: "HARD", audience: "GENERAL" },
  { civilian: "九牛一毛", undercover: "沧海一粟", category: "IDIOM", difficulty: "STANDARD", audience: "GENERAL" },
  { civilian: "瓜田李下", undercover: "避嫌", category: "IDIOM", difficulty: "HARD", audience: "GENERAL" },
  { civilian: "开门见山", undercover: "直截了当", category: "IDIOM", difficulty: "EASY", audience: "GENERAL" },

  // 游戏通用。
  { civilian: "排位赛", undercover: "匹配赛", category: "GAME", difficulty: "EASY", audience: "INTEREST" },
  { civilian: "单机游戏", undercover: "联机游戏", category: "GAME", difficulty: "EASY", audience: "INTEREST" },
  { civilian: "主机", undercover: "掌机", category: "GAME", difficulty: "EASY", audience: "INTEREST" },
  { civilian: "皮肤", undercover: "道具", category: "GAME", difficulty: "EASY", audience: "INTEREST" },
  { civilian: "存档点", undercover: "复活点", category: "GAME", difficulty: "STANDARD", audience: "INTEREST" },
  { civilian: "新手村", undercover: "主城", category: "GAME", difficulty: "STANDARD", audience: "INTEREST" },
  { civilian: "血条", undercover: "蓝条", category: "GAME", difficulty: "EASY", audience: "INTEREST" },
  { civilian: "暴击", undercover: "连击", category: "GAME", difficulty: "STANDARD", audience: "INTEREST" },
  { civilian: "副本", undercover: "秘境", category: "GAME", difficulty: "STANDARD", audience: "INTEREST" },
  { civilian: "团战", undercover: "遭遇战", category: "GAME", difficulty: "STANDARD", audience: "INTEREST" },
  { civilian: "坦克位", undercover: "治疗位", category: "GAME", difficulty: "STANDARD", audience: "INTEREST" },
  { civilian: "近战", undercover: "远程", category: "GAME", difficulty: "EASY", audience: "INTEREST" },
  { civilian: "任务奖励", undercover: "成就奖励", category: "GAME", difficulty: "STANDARD", audience: "INTEREST" },
  { civilian: "每日签到", undercover: "赛季通行证", category: "GAME", difficulty: "STANDARD", audience: "INTEREST" },
  { civilian: "开黑", undercover: "单排", category: "GAME", difficulty: "EASY", audience: "INTEREST" },
  { civilian: "补刀", undercover: "抢人头", category: "GAME", difficulty: "STANDARD", audience: "INTEREST" },
  { civilian: "草丛埋伏", undercover: "绕后偷袭", category: "GAME", difficulty: "STANDARD", audience: "INTEREST" },
  { civilian: "读条", undercover: "冷却", category: "GAME", difficulty: "HARD", audience: "INTEREST" },
  { civilian: "装备栏", undercover: "背包栏", category: "GAME", difficulty: "STANDARD", audience: "INTEREST" },
  { civilian: "游戏手柄", undercover: "机械键盘", category: "GAME", difficulty: "EASY", audience: "INTEREST" },
  { civilian: "回合制", undercover: "即时制", category: "GAME", difficulty: "STANDARD", audience: "INTEREST" },
  { civilian: "开放世界", undercover: "箱庭地图", category: "GAME", difficulty: "HARD", audience: "INTEREST" },
  { civilian: "剧情模式", undercover: "生存模式", category: "GAME", difficulty: "STANDARD", audience: "INTEREST" },
  { civilian: "隐藏关卡", undercover: "彩蛋房间", category: "GAME", difficulty: "HARD", audience: "INTEREST" },
  { civilian: "最终首领", undercover: "精英怪物", category: "GAME", difficulty: "STANDARD", audience: "INTEREST" },
  { civilian: "经验值", undercover: "熟练度", category: "GAME", difficulty: "STANDARD", audience: "INTEREST" },
  { civilian: "金币商店", undercover: "钻石商店", category: "GAME", difficulty: "EASY", audience: "INTEREST" },
  { civilian: "语音队友", undercover: "路人队友", category: "GAME", difficulty: "EASY", audience: "INTEREST" },
  { civilian: "游戏攻略", undercover: "速通视频", category: "GAME", difficulty: "STANDARD", audience: "INTEREST" },
  { civilian: "掉线重连", undercover: "强制退出", category: "GAME", difficulty: "STANDARD", audience: "INTEREST" },

  // 王者荣耀：按机制与体验配对，不只按职业。
  { civilian: "李白", undercover: "韩信", category: "HONOR_OF_KINGS", difficulty: "EASY", audience: "INTEREST" },
  { civilian: "后羿", undercover: "鲁班七号", category: "HONOR_OF_KINGS", difficulty: "EASY", audience: "INTEREST" },
  { civilian: "妲己", undercover: "安琪拉", category: "HONOR_OF_KINGS", difficulty: "EASY", audience: "INTEREST" },
  { civilian: "王昭君", undercover: "甄姬", category: "HONOR_OF_KINGS", difficulty: "STANDARD", audience: "INTEREST" },
  { civilian: "蔡文姬", undercover: "桑启", category: "HONOR_OF_KINGS", difficulty: "STANDARD", audience: "INTEREST" },
  { civilian: "瑶", undercover: "明世隐", category: "HONOR_OF_KINGS", difficulty: "STANDARD", audience: "INTEREST" },
  { civilian: "铠", undercover: "吕布", category: "HONOR_OF_KINGS", difficulty: "EASY", audience: "INTEREST" },
  { civilian: "孙悟空", undercover: "典韦", category: "HONOR_OF_KINGS", difficulty: "STANDARD", audience: "INTEREST" },
  { civilian: "兰陵王", undercover: "阿轲", category: "HONOR_OF_KINGS", difficulty: "STANDARD", audience: "INTEREST" },
  { civilian: "百里守约", undercover: "干将莫邪", category: "HONOR_OF_KINGS", difficulty: "HARD", audience: "INTEREST" },
  { civilian: "盾山", undercover: "公孙离", category: "HONOR_OF_KINGS", difficulty: "HARD", audience: "INTEREST" },
  { civilian: "钟馗", undercover: "玄策", category: "HONOR_OF_KINGS", difficulty: "HARD", audience: "INTEREST" },
  { civilian: "东皇太一", undercover: "张良", category: "HONOR_OF_KINGS", difficulty: "STANDARD", audience: "INTEREST" },
  { civilian: "大乔", undercover: "刘邦", category: "HONOR_OF_KINGS", difficulty: "HARD", audience: "INTEREST" },
  { civilian: "哪吒", undercover: "司马懿", category: "HONOR_OF_KINGS", difficulty: "HARD", audience: "INTEREST" },
  { civilian: "关羽", undercover: "马超", category: "HONOR_OF_KINGS", difficulty: "STANDARD", audience: "INTEREST" },
  { civilian: "花木兰", undercover: "元歌", category: "HONOR_OF_KINGS", difficulty: "HARD", audience: "INTEREST" },
  { civilian: "貂蝉", undercover: "上官婉儿", category: "HONOR_OF_KINGS", difficulty: "STANDARD", audience: "INTEREST" },
  { civilian: "诸葛亮", undercover: "不知火舞", category: "HONOR_OF_KINGS", difficulty: "STANDARD", audience: "INTEREST" },
  { civilian: "小乔", undercover: "沈梦溪", category: "HONOR_OF_KINGS", difficulty: "STANDARD", audience: "INTEREST" },
  { civilian: "黄忠", undercover: "伽罗", category: "HONOR_OF_KINGS", difficulty: "STANDARD", audience: "INTEREST" },
  { civilian: "虞姬", undercover: "狄仁杰", category: "HONOR_OF_KINGS", difficulty: "STANDARD", audience: "INTEREST" },
  { civilian: "马可波罗", undercover: "孙尚香", category: "HONOR_OF_KINGS", difficulty: "STANDARD", audience: "INTEREST" },
  { civilian: "项羽", undercover: "廉颇", category: "HONOR_OF_KINGS", difficulty: "EASY", audience: "INTEREST" },
  { civilian: "白起", undercover: "苏烈", category: "HONOR_OF_KINGS", difficulty: "STANDARD", audience: "INTEREST" },
  { civilian: "庄周", undercover: "孙膑", category: "HONOR_OF_KINGS", difficulty: "STANDARD", audience: "INTEREST" },
  { civilian: "鬼谷子", undercover: "鲁班大师", category: "HONOR_OF_KINGS", difficulty: "HARD", audience: "INTEREST" },
  { civilian: "云中君", undercover: "娜可露露", category: "HONOR_OF_KINGS", difficulty: "HARD", audience: "INTEREST" },
  { civilian: "露娜", undercover: "镜", category: "HONOR_OF_KINGS", difficulty: "HARD", audience: "INTEREST" },
  { civilian: "程咬金", undercover: "猪八戒", category: "HONOR_OF_KINGS", difficulty: "EASY", audience: "INTEREST" },

  // 汽车。
  { civilian: "宝马", undercover: "奔驰", category: "CAR", difficulty: "EASY", audience: "INTEREST" },
  { civilian: "奥迪", undercover: "沃尔沃", category: "CAR", difficulty: "EASY", audience: "INTEREST" },
  { civilian: "特斯拉", undercover: "比亚迪", category: "CAR", difficulty: "EASY", audience: "INTEREST" },
  { civilian: "蔚来", undercover: "理想", category: "CAR", difficulty: "STANDARD", audience: "INTEREST" },
  { civilian: "小鹏", undercover: "零跑", category: "CAR", difficulty: "STANDARD", audience: "INTEREST" },
  { civilian: "丰田", undercover: "本田", category: "CAR", difficulty: "EASY", audience: "INTEREST" },
  { civilian: "大众", undercover: "别克", category: "CAR", difficulty: "EASY", audience: "INTEREST" },
  { civilian: "保时捷", undercover: "玛莎拉蒂", category: "CAR", difficulty: "STANDARD", audience: "INTEREST" },
  { civilian: "法拉利", undercover: "兰博基尼", category: "CAR", difficulty: "EASY", audience: "INTEREST" },
  { civilian: "路虎", undercover: "吉普", category: "CAR", difficulty: "STANDARD", audience: "INTEREST" },
  { civilian: "SUV", undercover: "MPV", category: "CAR", difficulty: "EASY", audience: "INTEREST" },
  { civilian: "轿车", undercover: "旅行车", category: "CAR", difficulty: "STANDARD", audience: "INTEREST" },
  { civilian: "跑车", undercover: "敞篷车", category: "CAR", difficulty: "EASY", audience: "INTEREST" },
  { civilian: "越野车", undercover: "皮卡", category: "CAR", difficulty: "STANDARD", audience: "INTEREST" },
  { civilian: "新能源车", undercover: "燃油车", category: "CAR", difficulty: "EASY", audience: "INTEREST" },
  { civilian: "纯电动", undercover: "插电混动", category: "CAR", difficulty: "STANDARD", audience: "INTEREST" },
  { civilian: "快充", undercover: "慢充", category: "CAR", difficulty: "EASY", audience: "INTEREST" },
  { civilian: "自动泊车", undercover: "定速巡航", category: "CAR", difficulty: "STANDARD", audience: "INTEREST" },
  { civilian: "倒车影像", undercover: "全景影像", category: "CAR", difficulty: "STANDARD", audience: "INTEREST" },
  { civilian: "安全气囊", undercover: "安全带", category: "CAR", difficulty: "EASY", audience: "INTEREST" },
  { civilian: "方向盘", undercover: "换挡杆", category: "CAR", difficulty: "EASY", audience: "INTEREST" },
  { civilian: "刹车踏板", undercover: "油门踏板", category: "CAR", difficulty: "EASY", audience: "INTEREST" },
  { civilian: "天窗", undercover: "遮阳帘", category: "CAR", difficulty: "STANDARD", audience: "INTEREST" },
  { civilian: "后备箱", undercover: "前备箱", category: "CAR", difficulty: "STANDARD", audience: "INTEREST" },
  { civilian: "轮胎", undercover: "轮毂", category: "CAR", difficulty: "EASY", audience: "INTEREST" },
  { civilian: "发动机", undercover: "电动机", category: "CAR", difficulty: "STANDARD", audience: "INTEREST" },
  { civilian: "涡轮增压", undercover: "自然吸气", category: "CAR", difficulty: "HARD", audience: "INTEREST" },
  { civilian: "四驱", undercover: "前驱", category: "CAR", difficulty: "HARD", audience: "INTEREST" },
  { civilian: "车钥匙", undercover: "无钥匙进入", category: "CAR", difficulty: "STANDARD", audience: "INTEREST" },
  { civilian: "洗车", undercover: "打蜡", category: "CAR", difficulty: "EASY", audience: "INTEREST" },

  // 医学健康补充到可独立选择的规模。
  { civilian: "门诊", undercover: "急诊", category: "MEDICAL", difficulty: "EASY", audience: "INTEREST" },
  { civilian: "X光", undercover: "CT", category: "MEDICAL", difficulty: "EASY", audience: "INTEREST" },
  { civilian: "感冒", undercover: "过敏", category: "MEDICAL", difficulty: "EASY", audience: "INTEREST" },
  { civilian: "听诊器", undercover: "血压计", category: "MEDICAL", difficulty: "EASY", audience: "INTEREST" },
  { civilian: "创可贴", undercover: "纱布", category: "MEDICAL", difficulty: "EASY", audience: "INTEREST" },
  { civilian: "药片", undercover: "胶囊", category: "MEDICAL", difficulty: "EASY", audience: "INTEREST" },
  { civilian: "输液", undercover: "打针", category: "MEDICAL", difficulty: "EASY", audience: "INTEREST" },
  { civilian: "验血", undercover: "验尿", category: "MEDICAL", difficulty: "STANDARD", audience: "INTEREST" },
  { civilian: "发烧", undercover: "中暑", category: "MEDICAL", difficulty: "STANDARD", audience: "INTEREST" },
  { civilian: "咳嗽", undercover: "打喷嚏", category: "MEDICAL", difficulty: "EASY", audience: "INTEREST" },
  { civilian: "骨折", undercover: "扭伤", category: "MEDICAL", difficulty: "EASY", audience: "INTEREST" },
  { civilian: "近视", undercover: "散光", category: "MEDICAL", difficulty: "STANDARD", audience: "INTEREST" },
  { civilian: "拔牙", undercover: "补牙", category: "MEDICAL", difficulty: "EASY", audience: "INTEREST" },
  { civilian: "麻醉", undercover: "镇痛", category: "MEDICAL", difficulty: "STANDARD", audience: "INTEREST" },
  { civilian: "住院", undercover: "留观", category: "MEDICAL", difficulty: "STANDARD", audience: "INTEREST" },
  { civilian: "处方药", undercover: "非处方药", category: "MEDICAL", difficulty: "STANDARD", audience: "INTEREST" },
  { civilian: "康复训练", undercover: "体育锻炼", category: "MEDICAL", difficulty: "STANDARD", audience: "INTEREST" },
  { civilian: "心电图", undercover: "脑电图", category: "MEDICAL", difficulty: "HARD", audience: "INTEREST" },
  { civilian: "内科", undercover: "外科", category: "MEDICAL", difficulty: "EASY", audience: "INTEREST" },
  { civilian: "消毒", undercover: "灭菌", category: "MEDICAL", difficulty: "HARD", audience: "INTEREST" },
];

function categoryForBaseIndex(index: number): WordCategory {
  if (index < 30 || (index >= 270 && index < 300)) return "FOOD";
  if (index < 60 || (index >= 210 && index < 270)) return "DAILY";
  if (index < 90) return "ANIMAL_NATURE";
  if (index < 120 || (index >= 350 && index < 360)) return "ENTERTAINMENT";
  if (index < 150 || (index >= 330 && index < 350)) return "TECH";
  if (index < 180 || (index >= 300 && index < 330)) return "TRAVEL";
  if (index < 210) return "SCHOOL_WORK";
  if (index < 390) return "SCIENCE";
  return "MEDICAL";
}

function difficultyForBaseIndex(index: number): WordDifficulty {
  return index % 5 === 0 ? "EASY" : index % 5 === 4 ? "HARD" : "STANDARD";
}

const taggedBasePairs: readonly WordPair[] = BASE_PAIRS.map((pair, index) => {
  const category = categoryForBaseIndex(index);
  return {
    ...pair,
    category,
    difficulty: difficultyForBaseIndex(index),
    audience: ["TECH", "MEDICAL", "SCIENCE"].includes(category) ? "INTEREST" : "GENERAL",
  } as WordPair;
});

export const WORD_PAIRS: readonly WordPair[] = [...taggedBasePairs, ...CURATED_PAIRS];

export function filterWordPairs(category: WordCategory, difficulty: WordDifficulty): WordPair[] {
  return WORD_PAIRS.filter((pair) => {
    const categoryMatches = category === "GENERAL" ? pair.audience === "GENERAL" : pair.category === category;
    return categoryMatches && pair.difficulty === difficulty;
  });
}
